Repository scenarigo/scenarigo, pull requests merged in 2025-07, with the labels that each got.

#575 bump golangci-lint to v2.2.1
  .github/workflows/reviewdog.yml
  .golangci.yml
  Makefile
  cmd/scenarigo/cmd/plugin/build.go
  cmd/scenarigo/cmd/run_test.go
  mock/protocol/protocol.go
  protocol/grpc/grpc_oneof_test.go
  protocol/http/request.go
  reporter/reporter_teardown_test.go
  schema/load.go
  schema/yaml.go
Labels: chore

#576 batch output to prevent write conflicts
  reporter/reporter.go
Labels: bug fix

#577 fix parallel flag
  cmd/scenarigo/cmd/run.go
Labels: bug fix

#584 Add plugin/testdata/wasm/src directory to target for dependabot
  .github/dependabot.yml
Labels: chore

#587 sort parallel output
  context/steps_test.go
  internal/testutil/normalize_parallel_output.go
  internal/testutil/normalize_parallel_output_test.go
  reporter/reporter_teardown_test.go
Labels: chore

#588 bump dependencies
  .github/workflows/bump-indirect-modules.yml
  examples/assert/plugin/src/go.mod
  examples/assert/plugin/src/go.sum
  examples/default-value-with-nullish-coalescing-operator/plugin/src/go.mod
  examples/default-value-with-nullish-coalescing-operator/plugin/src/go.sum
  examples/grpc/plugin/src/go.mod
  examples/grpc/plugin/src/go.sum
  examples/secrets/plugin/src/go.mod
  examples/secrets/plugin/src/go.sum
  examples/step-if/plugin/src/go.mod
  examples/step-if/plugin/src/go.sum
  examples/wasm/plugin/src/go.mod
  examples/wasm/plugin/src/go.sum
  examples/ytt/plugin/src/go.mod
  examples/ytt/plugin/src/go.sum
  go.mod
  go.sum
  plugin/testdata/wasm/src/go.mod
  plugin/testdata/wasm/src/go.sum
  plugin/wasm_host_test.go
Labels: dependencies
